# generated by Gemini 2.5 Flash
import json
import os
import subprocess
import sys
import time
from pathlib import Path

from dotenv import load_dotenv
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

REPO_ROOT = Path(__file__).resolve().parent.parent

# --- Load Environment Variables ---
# This looks for and loads variables from a .env file in the current directory
load_dotenv()

# --- Configuration ---
# 1. Load the API Key from the environment file
API_KEY = os.getenv("YOUTUBE_API_KEY")
# Check if the key was loaded successfully
if not API_KEY:
    raise ValueError(
        "YOUTUBE_API_KEY not found. Please create a .env file and set the variable."
    )

# 3. Maximum videos to retrieve (max 500 across 10 requests is a common API limit)
TARGET_VIDEO_COUNT = 50
# 4. Define paths (anchored at repo root, regardless of CWD)
OUTPUT_DIR = str(REPO_ROOT / "dataset")
VIDEO_DIR = os.path.join(OUTPUT_DIR, "videos")
JSON_FILE = os.path.join(OUTPUT_DIR, "video_data")
COOKIE_FILE = str(REPO_ROOT / "cookies.txt")

# Create output directories if they don't exist
os.makedirs(VIDEO_DIR, exist_ok=True)

# --- Cookie Check Function ---


def check_and_exit_if_cookies_missing(cookie_file_path):
    """
    Checks for the presence of the cookie file and exits with instructions if missing.
    """
    if not os.path.exists(cookie_file_path):
        print("=" * 70)
        print("🚨 **AUTHENTICATION REQUIRED: COOKIE FILE MISSING** 🚨")
        print("=" * 70)
        print(
            f"To download more than ~80 videos, you must provide a valid session file."
        )
        print(
            f"The required file **'{cookie_file_path}'** was not found in the current directory."
        )
        print("\n**STEP 1: Create the cookies.txt file**")
        print("1. Log into YouTube in your browser.")
        print(
            "2. Install a browser extension to export cookies (e.g., 'Get cookies.txt' or 'Cookie-Editor')."
        )
        print("3. Use the extension to export your current YouTube session cookies.")
        print(
            f"4. Save the exported data as a file named **'{cookie_file_path}'** in this directory."
        )
        print(
            "5. Make sure you have access to some js runtime like deno, see https://github.com/yt-dlp/yt-dlp/wiki/EJS"
        )
        print("\n**STEP 2: Rerun the script**")
        print("Once the file is created, run the script again.")
        print("=" * 70)
        sys.exit(1)  # Exit the script
    else:
        print(
            f"✅ Found **{cookie_file_path}**. Continuing with authenticated download."
        )


# --- 1. API Scraping and Pagination (Unchanged) ---


def get_videos(api_key, target_count, source_class, query):
    """
    Retrieves trending videos, handling pagination to reach the target count.
    (This function is the same as the previous script, using the official API.)
    """
    print(f"🔥 Starting API scrape for {target_count} trending videos ...")

    youtube = build("youtube", "v3", developerKey=api_key)
    all_videos = []
    next_page_token = None

    # check if id was already scraped, sometimes videos get returned in two distinct pages
    ids = set()

    # The API limit per request is 50. Loop until we hit the target count.
    while len(all_videos) < target_count:
        max_results = 50

        try:
            request = youtube.search().list(
                part="id,snippet",
                safeSearch="none",
                relevanceLanguage="en",
                q=query,
                type="video",
                maxResults=max_results,
                pageToken=next_page_token,
                videoDuration="short",
                publishedAfter="2026-01-01T00:00:00Z",
                publishedBefore="2026-03-31T23:59:59Z",
                order="relevance",  # relevance, viewCount
            )
            response = request.execute()

        except HttpError as e:
            print(f"\n❌ API Error on page {len(all_videos) // 50 + 1}: {e}")
            break

        next_page_token = response.get("nextPageToken")
        for video_item in response.get("items", []):
            try:
                request = youtube.videos().list(
                    # Ensure 'contentDetails' is requested to get the duration
                    part="snippet,statistics,contentDetails",
                    id=video_item["id"]["videoId"],
                    maxResults=1,
                )
                response = request.execute()
            except HttpError as e:
                print(f"\n❌ API Error on page {len(all_videos) // 50 + 1}: {e}")
                continue
            item = response["items"][0]
            video_id = item["id"]
            if "snippet" not in item or "contentDetails" not in item:
                print(
                    f"   Skipping video {video_id}: Snippet or details not available."
                )
                continue
            if "duration" not in item["contentDetails"]:
                print(f"   Skipping video {video_id}: duration not available.")
                continue
            if "M" in item["contentDetails"]["duration"]:
                print(
                    f"   Skipping video {video_id}: too long. ({item['contentDetails']['duration']})"
                )
                continue
            if item["snippet"]["liveBroadcastContent"] == "live":
                print(f"   Skipping video {video_id}: live stream.")
                continue

            video_info = {
                "rank": len(all_videos) + 1,
                "video_id": video_id,
                "source_class": source_class,
                "source_query": query,
                "title": item["snippet"]["title"],
                "published_at": item["snippet"]["publishedAt"],
                "channel_title": item["snippet"]["channelTitle"],
                "category_id": item["snippet"]["categoryId"],
                "view_count": item["statistics"].get("viewCount", "0"),
                "like_count": item["statistics"].get("likeCount", "0"),
                "duration": item["contentDetails"]["duration"],
                "url": f"https://www.youtube.com/watch?v={video_id}",
                "local_filepath": None,
            }
            if video_id not in ids:
                all_videos.append(video_info)
                ids.add(video_id)
            if len(all_videos) == target_count:
                break

        print(f"   -> Fetched {len(all_videos)} videos so far...")

        if not next_page_token or len(all_videos) >= target_count:
            break

    print(f"✅ API Scrape complete. Total videos retrieved: {len(all_videos)}")
    return all_videos


# --- 2. Video Downloading with yt-dlp ---


def download_video_with_ytdlp(video_id, output_path):
    """
    Downloads the YouTube video using the yt-dlp command-line tool.
    Returns the expected local filename on success, or None on failure.
    """
    video_url = f"https://www.youtube.com/watch?v={video_id}"
    filename_template = f"{video_id}.mp4"
    full_output_path = os.path.join(output_path, filename_template)
    if os.path.exists(full_output_path) and os.path.getsize(full_output_path) > 0:
        print("    File already downloaded, skipping!")
        return full_output_path

    print(f"   Downloading Video ID: {video_id}...")

    # yt-dlp command structure:
    # -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best: Selects the best quality streams
    # --merge-output-format mp4: Ensures the final merged file is MP4
    # -o ...: Specifies the output template (path and filename)
    command = [
        "yt-dlp",
        "--cookies-from-browser",
        "firefox",
        "--remote-components",
        "ejs:github",
        "-f",
        "[aspect_ratio=0.56]+bestvideo[ext=mp4]+bestaudio[ext=m4a]/best",
        "--merge-output-format",
        "mp4",
        "-o",
        full_output_path,
        video_url,
    ]

    try:
        # Execute the yt-dlp command
        result = subprocess.run(command, check=True, capture_output=True, text=True)

        # Check if the file was actually created and is not empty (simple check)
        if os.path.exists(full_output_path) and os.path.getsize(full_output_path) > 0:
            return full_output_path
        else:
            # This handles cases where yt-dlp succeeds but the file size is zero
            print(
                f"   ❌ Error: Download command succeeded but file is empty or missing. Most likely the video was not in 9:16 format and thus skipped."
            )
            print("   yt-dlp stdout:", result.stdout)
            return None

    except subprocess.CalledProcessError as e:
        # yt-dlp returned a non-zero exit code (i.e., failed)
        print(f"   ❌ yt-dlp failed for {video_id} (Code {e.returncode}).")
        print("   Error output:", e.stderr)
    except FileNotFoundError:
        # Happens if 'yt-dlp' command is not found (not installed or not in PATH)
        print(
            "   ❌ Error: 'yt-dlp' command not found. Ensure it is installed and in your PATH."
        )
    except Exception as e:
        print(f"   ❌ An unexpected error occurred: {e}")

    return None


def download_and_save_data(videos_list):
    """
    Downloads videos using yt-dlp, updates the list with file paths, and saves everything to JSON.
    """
    print(
        f"\n🎥 Starting video download process for {len(videos_list)} videos with yt-dlp..."
    )

    for i, video in enumerate(videos_list):
        print(f"[{i+1}/{len(videos_list)}] Title: {video['title']}")

        # Download the video and get the local path
        local_path = download_video_with_ytdlp(video["video_id"], VIDEO_DIR)

        if local_path:
            # Save the relative path in the JSON for portability
            relative_path = os.path.join(
                os.path.basename(VIDEO_DIR), os.path.basename(local_path)
            )
            video["local_filepath"] = relative_path
            print(f"   Saved successfully to: {relative_path}")
        else:
            video["local_filepath"] = "DOWNLOAD_FAILED"

        print("-" * 20)


# --- Main Execution ---

if __name__ == "__main__":

    # 0. Check for the cookie file first!
    # check_and_exit_if_cookies_missing(COOKIE_FILE)

    # 1. Scrape the Trending Videos data from the API
    classes_queries = {
        "Animal": [
            '"cute pet tricks" | "wildlife footage" | "animal rescue vlog" | "livestock care"',
            '"cat POV" | "dog sleeping" | "veterinary procedure" | "nature cam" -hunting',
            '"#animalshorts" | "#petsoftiktok" | "#wildlife" | "#cuteanimals"',
            '"#dogtraining" | "#catsoftiktok" | "#vetmed" | "#farmlife" | "#animals"',
        ],
        "Car": [
            '"car review" | "exhaust sound" | "car detailing ASMR" | "JDM car meet edit" -GTA',
            '"engine swap tutorial" | "car aesthetic edit" | "POV driving speed" -GTA -podcast -storytime',
            '"#carcommunity" | "#jdm" | "#caredit" | "#supercars" | "#carscene" -GTA',
            '"#mechanic" | "#exhaust" | "#carculture" | "#povdrive" -GTA -podcast',
        ],
    }
    for source_class in classes_queries:
        for i, query in enumerate(classes_queries[source_class]):
            videos = get_videos(API_KEY, TARGET_VIDEO_COUNT, source_class, query)

            if videos:
                # 2. Download the videos and save the master JSON file
                # Save the final data structure to JSON
                with open(
                    f"{JSON_FILE}_{source_class}_{i}.json", "w", encoding="utf-8"
                ) as f:
                    json.dump(videos, f, ensure_ascii=False, indent=4)

                download_and_save_data(videos)
                print(
                    f"\n✅ All video information of {source_class}, query {i} saved to: **{JSON_FILE}**"
                )
            else:
                print(
                    "Script finished without results due to API errors or zero videos found."
                )
